# Generated by Django 5.0.6 on 2024-06-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='discriptions',
            new_name='description',
        ),
    ]
