# Generated by Django 5.0.6 on 2024-07-09 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='сategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='task.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
