# Generated by Django 5.0.6 on 2024-07-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_сategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='сategory',
            new_name='category',
        ),
    ]
